set shell := ["bash", "-cu"]

# drape publishes to PyPI via GitHub Actions OIDC (release.yml). `just release`
# tags + pushes; the tag push triggers the workflow that uploads to PyPI.
# CHANGELOG.md is generated by git-cliff inside `release-kit cut`.
import 'release.just'

# List recipes
default:
    @just --list

# Run tests
test:
    uv run pytest

# Run linters + type checks
check:
    uv run ruff check .
    uv run black --check .
    uv run mypy src/drape

# Auto-format
fmt:
    uv run ruff check --fix .
    uv run black .

# Cut a release. Build and PyPI publish happen automatically via GitHub Actions
# OIDC after the tag push (release.yml). Alias: `just tag LEVEL`.
ship level:
    @just release {{level}}
