#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12", "httpx>=0.27"]
# ///
"""Publish drape to PyPI. Generated by project-kit."""
from __future__ import annotations

import subprocess

import httpx
import typer

PYPI_PACKAGE = "drape"

app = typer.Typer(add_completion=False)


@app.command()
def main(
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if status:
        r = httpx.get(f"https://pypi.org/pypi/{PYPI_PACKAGE}/json", timeout=10)
        if r.status_code == 200:
            typer.echo(r.json()["info"]["version"])
        else:
            typer.echo(f"not found on PyPI: {PYPI_PACKAGE}", err=True)
            raise typer.Exit(code=1)
        return
    if rollback:
        typer.echo("PyPI does not support rollback. Yank manually with: pip yank …", err=True)
        raise typer.Exit(code=1)
    if dry_run:
        typer.echo("[dry-run] would run: uv build && uv publish")
        return
    typer.echo(f"building + publishing {PYPI_PACKAGE} (env={env})…")
    subprocess.run(["uv", "build"], check=True)
    subprocess.run(["uv", "publish"], check=True)


if __name__ == "__main__":
    app()
