#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12"]
# ///
"""Custom deploy for drape. Generated by project-kit.

Runs user-supplied command verbatim. The command was specified at scaffold time
and is trusted.
"""
from __future__ import annotations

import subprocess

import typer

CUSTOM_COMMAND = "echo no custom command configured"

app = typer.Typer(add_completion=False)


@app.command()
def main(
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if rollback or status:
        typer.echo(
            "custom deploys do not support --rollback or --status; "
            "handle manually or edit this script",
            err=True,
        )
        raise typer.Exit(code=1)
    if dry_run:
        typer.echo(f"[dry-run] would run (env={env}):\n  {CUSTOM_COMMAND}")
        return
    subprocess.run(CUSTOM_COMMAND, shell=True, check=True)


if __name__ == "__main__":
    app()
