#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12"]
# ///
"""Deploy drape to homelab. Generated by project-kit.

Delegates to ~/Documents/Homelab/apps/None/justfile.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import typer

HOMELAB_APP = "None"
HOMELAB_PATH = Path.home() / "Documents" / "Homelab" / "apps" / HOMELAB_APP

app = typer.Typer(add_completion=False)


def _tag() -> str:
    return subprocess.run(
        ["git", "describe", "--tags", "--abbrev=0"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()


@app.command()
def main(
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if not HOMELAB_PATH.is_dir():
        typer.echo(f"error: homelab app path missing: {HOMELAB_PATH}", err=True)
        raise typer.Exit(code=1)
    if status:
        subprocess.run(
            ["docker", "inspect", HOMELAB_APP, "--format", "{{.Config.Image}}"],
            check=False,
        )
        return
    if rollback:
        # last-but-one tag
        tags = subprocess.run(
            ["git", "tag", "--sort=-creatordate"],
            check=True, capture_output=True, text=True,
        ).stdout.split()
        if len(tags) < 2:
            typer.echo("error: no previous tag to rollback to", err=True)
            raise typer.Exit(code=1)
        target_tag = tags[1]
    else:
        target_tag = _tag()
    if dry_run:
        typer.echo(f"[dry-run] would cd {HOMELAB_PATH} && just deploy {target_tag}")
        return
    typer.echo(f"deploying {HOMELAB_APP} tag={target_tag} env={env}…")
    subprocess.run(["just", "deploy", target_tag], cwd=HOMELAB_PATH, check=True)


if __name__ == "__main__":
    app()
