#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12"]
# ///
"""Push drape to GHCR. Generated by project-kit."""
from __future__ import annotations

import subprocess

import typer

REGISTRY = "ghcr.io/pike00"
IMAGE_NAME = "drape"

app = typer.Typer(add_completion=False)


def _short_sha() -> str:
    return subprocess.run(
        ["git", "rev-parse", "--short", "HEAD"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()


@app.command()
def main(
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if status:
        subprocess.run(
            ["docker", "manifest", "inspect", f"{REGISTRY}/{IMAGE_NAME}:latest"],
            check=False,
        )
        return
    if rollback:
        tags = subprocess.run(
            ["git", "tag", "--sort=-creatordate"],
            check=True, capture_output=True, text=True,
        ).stdout.split()
        if len(tags) < 2:
            typer.echo("no previous tag to rollback to", err=True)
            raise typer.Exit(code=1)
        prev_sha = subprocess.run(
            ["git", "rev-parse", "--short", tags[1]],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
        if dry_run:
            typer.echo(f"[dry-run] would retag :latest -> {prev_sha}")
            return
        subprocess.run(
            ["docker", "buildx", "imagetools", "create",
             f"{REGISTRY}/{IMAGE_NAME}:{prev_sha}",
             "-t", f"{REGISTRY}/{IMAGE_NAME}:latest"],
            check=True,
        )
        return
    sha = _short_sha()
    if dry_run:
        typer.echo(f"[dry-run] would just build-image -> :{sha} + :latest (env={env})")
        return
    subprocess.run(["just", "build-image"], check=True)


if __name__ == "__main__":
    app()
