#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = ["typer>=0.12"]
# ///
"""Deploy drape to Cloudflare Workers. Generated by project-kit."""
from __future__ import annotations

import subprocess

import typer

CF_WORKER = "drape"

app = typer.Typer(add_completion=False)


@app.command()
def main(
    env: str = typer.Option("prod", "--env"),
    dry_run: bool = typer.Option(False, "--dry-run"),
    rollback: bool = typer.Option(False, "--rollback"),
    status: bool = typer.Option(False, "--status"),
) -> None:
    if status:
        subprocess.run(
            ["wrangler", "deployments", "list", "--name", CF_WORKER],
            check=False,
        )
        return
    if rollback:
        if dry_run:
            typer.echo(f"[dry-run] would: wrangler rollback --name {CF_WORKER}")
            return
        subprocess.run(["wrangler", "rollback", "--name", CF_WORKER], check=True)
        return
    if dry_run:
        typer.echo(f"[dry-run] would: wrangler deploy --name {CF_WORKER} (env={env})")
        return
    subprocess.run(["wrangler", "deploy", "--name", CF_WORKER], check=True)


if __name__ == "__main__":
    app()
