#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = [
#   "typer>=0.12",
#   "httpx>=0.27",
# ]
# ///
"""Push branch, wait for worktree health, create draft PR.

Generated by project-kit for drape.
"""
from __future__ import annotations

import subprocess
import time
from pathlib import Path

import httpx
import typer

PROJECT_NAME = "drape"
BRANCH = "main"
HOST_PATTERN = "None"
HEALTH_PATH = "/"
DOMAIN = "khanpikehome.com"

app = typer.Typer(add_completion=False)


def _run(cmd: list[str]) -> str:
    return subprocess.run(cmd, check=True, capture_output=True, text=True).stdout.strip()


def _slug_from_worktree() -> str:
    cwd = Path.cwd()
    parts = cwd.parts
    for i, p in enumerate(parts):
        if p == ".worktrees" and i + 1 < len(parts):
            return parts[i + 1]
    raise typer.BadParameter(f"not inside a .worktrees/<slug>/ path (cwd={cwd})")


@app.command()
def main(timeout: int = typer.Option(120, "--timeout", help="health-check timeout seconds")) -> None:
    slug = _slug_from_worktree()
    branch = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    typer.echo(f"[1/4] pushing branch {branch}…")
    subprocess.run(["git", "push", "-u", "origin", branch], check=True)

    url = "https://" + HOST_PATTERN.replace("{slug}", slug).replace("{domain}", DOMAIN) + HEALTH_PATH
    typer.echo(f"[2/4] waiting for health check at {url} (timeout {timeout}s)…")
    start = time.monotonic()
    while time.monotonic() - start < timeout:
        try:
            r = httpx.get(url, timeout=5, follow_redirects=True)
            if r.status_code < 400:
                typer.echo(f"       healthy in {int(time.monotonic() - start)}s")
                break
        except httpx.HTTPError:
            pass
        time.sleep(3)
    else:
        typer.echo(f"error: health check timed out at {url}", err=True)
        raise typer.Exit(code=1)

    typer.echo("[3/4] gathering commit log…")
    log = _run(["git", "log", f"{BRANCH}..HEAD", "--pretty=format:- %h %s"])
    n_commits = log.count("\n") + 1 if log else 0
    typer.echo(f"       {n_commits} commits ahead of {BRANCH}")

    typer.echo("[4/4] creating draft PR…")
    title = _run(["git", "log", "-1", "--pretty=%s"])
    body = f"Preview: {url}\n\nCommits:\n{log}\n"
    subprocess.run(
        ["gh", "pr", "create", "--draft", "--title", title, "--body", body, "--base", BRANCH],
        check=True,
    )


if __name__ == "__main__":
    app()
